# Generated by Django 5.2.15 on 2026-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0030_backfill_new_catalog_courseruns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='start',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
