# Finds code problems by structural pattern matching.
#
# New rules can be added to test_root/semgrep/ and they should be picked up
# automatically. See https://semgrep.dev/docs/ for documentation.

name: Semgrep code quality

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  run_semgrep:
    name: Semgrep analysis
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Install semgrep
        run: uv sync --project scripts/semgrep --frozen

      - name: Run semgrep
        env:
          # Peg this to some reasonable value so that semgrep's rewrapping
          # of messages doesn't break up lines in an unpredictable manner:
          # https://github.com/returntocorp/semgrep/issues/8608
          COLUMNS: 80
        run: |
          uv run --project scripts/semgrep semgrep scan --config test_root/semgrep/ --error --quiet \
            -- lms cms common openedx
